### ISSUE TITLE
Example with koa-router doesn't work

### ISSUE THREAD

**Issue by kaimiyang** [dlau/koa-body#90]
**"koa-router": "^7.3.0"**

this is version, app.use can work, but router not work!!!

**Comment by mengdu** [comment]
I got the same problem.
...
app.use(KoaBodyParser())
```js
router.all('/api/file', KoaBody(), async ctx => {
  ctx.body = {
    api: true,
    type: ctx.method,
    query: ctx.query,
    body: ctx.request.body,
    files: ctx.request.body.files
  }
})
```

**"koa":"2.5.1"**
**"koa-router"**: "7.4.0"
**"koa-body"**:"2.6.0"

**Comment by MarkHerhold** [comment]
Can one of you provide a single file that reproduces the exact issue? Is there an error?

**Comment by mengdu** [comment]
@MarkHerhold 

My problem is that when the `Content-type`  is `application/x-www-form-urlencoded` it does not respond to the.

code:

```js
app.use(KoaBodyParser())

router.all('/api/file', KoaBody(), async ctx => {
  ctx.body = {
    api: true,
    type: ctx.method,
    query: ctx.query,
    body: ctx.request.body,
    files: ctx.request.body.files
  }
})
```

When the code is `app.use(KoaBodyParser())`  othor router it dose not work !

**Comment by kaimiyang** [comment]
@MarkHerhold 
`
const router = new Router()
router.use('/upload', KoaBody({ multipart: true }), async ctx => {
  console.log(ctx.request.body);
})
`
or use router.post and etc, it not work, but use `app.use`, encountered the same problem @damianb, other routers await to loading. 

use koa-router, maybe router.use `parameters` is error, and not run next() other middleware

**Comment by Chen-WeiZhen** [comment]
the same with me ,the result of  `console.log(ctx.request.body.files) ` is undefined , i have already to upload a picture.

**Comment by Chen-WeiZhen** [comment]
how to resolve this problem ??

**Comment by scragg0x** [comment]
@Chen-WeiZhen files was moved to `ctx.request.files` in the latest version.

**Comment by gugu** [comment]
Whet I try to use koa-body in router, I get this exception:
```
error:  message=next is not a function, stack=TypeError: next is not a function
at /srv/.../node_modules/koa-body/index.js:110:14
at process._tickCallback (internal/process/next_tick.js:68:7)
```

in app level it works fine. My params:
```
koaBody({
    json: false,
    text: false,
})
```

**Comment by MarkHerhold** [comment]
@kaimiyang I'm still not exactly sure what the issue you are facing is. My speculation is that you aren't correctly initializing your router before trying to use it.

This minimal example works for me:
```js
var log       = console.log,
    Koa       = require('koa'),
    app       = new Koa(),
    router    = require('koa-router'),
    koaBody   = require('../index'),
    port      = process.env.PORT || 4291
    host      = process.env.HOST || 'http://localhost';

/*!
 * Accepts only urlencoded and json bodies.
 */
router.post('/upload', koaBody(), async (ctx) => {
    console.log(ctx.request.body);
  }
);

app.use(router.routes());
app.listen(port);

log('Test with executing this commands:');
log('curl -i %s:%s/post/users -d "user=admin"', host, port);
log('Press CTRL+C to stop...');
```

@gugu please open a separate issue and include your version of both koa-body and koa-router.

Both of you, please see the [koa-router example here](https://github.com/dlau/koa-body/blob/master/examples/koa-router.js).
